# Generated by Django 4.1.1 on 2022-09-09 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="issued_date",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
