# Generated by Django 4.1.1 on 2022-09-09 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_alter_certificate_issued_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="issued_date",
            field=models.DateField(default=datetime.date(2022, 9, 9), null=True),
        ),
    ]
