# Generated by Django 4.1.1 on 2022-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0003_alter_certificate_issued_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="issued_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
