# Generated by Django 4.1.1 on 2022-09-14 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_user_institute_address_alter_certificate_issued_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="institute_address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="institute_logo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="institute_name",
        ),
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute_name", models.CharField(blank=True, max_length=100)),
                ("institute_logo", models.ImageField(blank=True, upload_to="logos/")),
                ("institute_address", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
